### PR TITLE
Handle Figure visibility

### LINKED ISSUE #70: messenger / ZMQ session error upon "Matlab clear all" using 'magic'
As outlined in #56 and #69 I manage to build ```pymatbridge-0.3-dev``` under WIndows 8.1 64 bit. I can start the ```matlabserver``` and pass back and forth variables between MATLAB and my iPython notebook (Anaconda 1.9.1, Python 2.7.6) using 'magic' (the ```x=x+1``` and ```a=[1,2,3]``` 
```
%%matlab -i a -o b,c
b = a + 3
c = b + 3
```
sort of examples)

However when trying to port a more complex example, 

```
%%matlab -o x,xf

%Author: Osama Ullah Khan,
%        Phd Student, University of Michigan-Ann Arbor.
%        Email: oukhan@umich.edu
%        Version: 1.0
%
%This code demonstrate compressive sensing example. In this
%example the signal is sparse in frequency domain and random samples
%are taken in time domain.

close all;
clear all;

%setup path for the subdirectories of l1magic
path(path, 'C:\MATLAB\R2013a\l1magic\Optimization');
path(path, 'C:\MATLAB\R2013a\l1magic\Data');


%length of the signal
N=1024;

%Number of random observations to take
K=256;

%Discrete frequency of two sinusoids in the input signal
k1=29;
k2=59;
k3=109;

n=0:N-1;

%Sparse signal in frequency domain.
x=sin(2*pi*(k1/N)*n)+sin(2*pi*(k2/N)*n)+sin(2*pi*(k3/N)*n);

xf=abs(fft(x));
```
my matlabserver fails: 
```
MATLAB is running in headless mode.  Figure windows will not be displayed.
 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
Socket created at: tcp://127.0.0.1:55555
Error using messenger
Error: ZMQ session not initialized

Error in matlabserver (line 30)
            messenger('respond', resp);
 
» 
```

I'd like to point out this exact snippet has been working flawlessly using ```pymatbridge-0.2``` and the 'old' communication protocol. 

I don't know if this is an issue of Windows or my build -- can pelase someone on a different OS try to replicate this behaviour?
Thanks!

EDIT: This seems to be due to the ```clear all;``` which seems to kill the matlabserver. I modified the issue title accordingly

### LINKED ISSUE #96: Matlab magic  "The pymatbridge module is not an IPython extension"
Hi, all

My platform is 
* Windows 7 64bit
* Python 2.7.8 64bit
* IPython 2.3.1
* Matlab 2011a 64bit
* Visual Studio 2010

I download the master source code, comment the win32 test out and, after installing, build the messenger *"messenger.mexw64"* myself using mex.

I run the following code:

    from pymatbridge import Matlab
    mlab = Matlab()
    mlab.start()
    results = mlab.run_code('a=1;')
    print(results)
    mlab.stop()

It works. Here is the output:

    Starting MATLAB on ZMQ socket tcp://127.0.0.1:55555
    Send 'exit' command to kill the server
    ...MATLAB started and connected!
    {u'content': {u'datadir': u'C:\\Users\\Admin\\AppData\\Local\\Temp\\MatlabData\\', u'code': u'a=1;', u'figures': [], u'stdout': u''}, u'success': u'true'}
    MATLAB closed

But when I use it in the IPython notebook, it shows

    In [2]: %load_ext pymatbridge
    The pymatbridge module is not an IPython extension.

Does anyone have a clue? 
Best

### LINKED ISSUE #99: imshow() on mac os x
This does not work:
```
%%matlab
image = imread('../mp.tif');
matlab_F = fft2(image);
F = log(abs(fftshift(matlab_F)));
imshow(F);
```

It does work in console (but only with omitted -nodisplay):
```
$ /Applications/MATLAB_R2014b.app/bin/matlab -nodesktop
 
                                    < M A T L A B (R) >
                          Copyright 1984-2014 The MathWorks, Inc.
                           R2014b (8.4.0.150421) 64-bit (maci64)
                                     September 15, 2014

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
>> image = imread('../mp.tif');
>> matlab_F = fft2(image);
>> F = log(abs(fftshift(matlab_F)));
>> imshow(F, [min(F(:)), max(F(:))]);
Warning: Image is too big to fit on screen; displaying at 17% 
> In initSize at 71
  In imshow at 309 
>> exit
$ /Applications/MATLAB_R2014b.app/bin/matlab -nodesktop -nodisplay

                                    < M A T L A B (R) >
                          Copyright 1984-2014 The MathWorks, Inc.
                           R2014b (8.4.0.150421) 64-bit (maci64)
                                     September 15, 2014

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
>> image = imread('../mp.tif');
>> matlab_F = fft2(image);
>> F = log(abs(fftshift(matlab_F)));
>> imshow(F, [min(F(:)), max(F(:))]);
Error using imshow (line 212)
IMSHOW unable to display image. 
```

I've tried setting Matlab().startup_options to only `-nodesktop` (matlab logo shows up, so startup_options are executed correctly), but the error is the same:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-ade840d015dc> in <module>()
----> 1 get_ipython().run_cell_magic(u'matlab', u'', u"image = imread('../mp.tif');\nmatlab_F = fft2(image);\nF = log(abs(fftshift(matlab_F)));\nimshow(F, [min(F(:)), max(F(:))]);")

/Users/arve/.virtualenvs/brew/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_cell_magic(self, magic_name, line, cell)
   2160             magic_arg_s = self.var_expand(line, stack_depth)
   2161             with self.builtin_trap:
-> 2162                 result = fn(magic_arg_s, cell)
   2163             return result
   2164 

/Users/arve/.virtualenvs/brew/lib/python2.7/site-packages/pymatbridge/matlab_magic.pyc in matlab(self, line, cell, local_ns)

/Users/arve/.virtualenvs/brew/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194 
    195         if callable(arg):

/Users/arve/.virtualenvs/brew/lib/python2.7/site-packages/pymatbridge/matlab_magic.pyc in matlab(self, line, cell, local_ns)
    215             e_s += "\n-----------------------"
    216             e_s += "\nAre you sure Matlab is started?"
--> 217             raise RuntimeError(e_s)
    218 
    219 

RuntimeError: There was an error running the code:
 image = imread('../mp.tif');
matlab_F = fft2(image);
F = log(abs(fftshift(matlab_F)));
imshow(F, [min(F(:)), max(F(:))]);
-----------------------
Are you sure Matlab is started?
```

The matlab version is 2014b, and here are the running process:
```
/Applications/MATLAB_R2014b.app/bin/maci64/../../Contents/MacOS/MATLAB_maci64 -r warning('off','all');addpath(genpath('/Users/arve/.virtualenvs/brew/lib/python2.7/site-packages/pymatbridge/matlab'));warning('on', 'all');matlabserver('ipc:///tmp/pymatbridge');exit -nodesktop
```
Any ideas?

### LINKED ISSUE #101: How to plot floating figures
Hi, How can I run "figure" in a ipython cell and get the figure on a floating window? Right now I get a blank space inline. I would like to plot an image and use matlab figure properties. I also have some custom tools on an interactive figure window. Is this possible?
Thanks

### LINKED ISSUE #132: imshow failed
When I have imshow in my .m function and call from python, it has the following error
Error using imshow (line 212)
IMSHOW unable to display image.

Error in myFunction (line 17)
imshow(im);

How can I display an image in .m function that is called from python?

### LINKED ISSUE #148: numpy dependency
numpy used to be an optional dependency, but it looks like as of recently the import was made unconditional. If we don't care about that (I used to but eh), it should probably be added to `requirements.txt`.

### PR DESCRIPTION
**Pull request by blink1073**
Make the `messenger` non-blocking, and allow Matlab GUI to refresh, making visible plots interactive.
Added the ability to toggle visibility through the `set_plot_settings` method or using the `--gui` flag in the magic.  The Matlab splash screen will now pop up at the start, but the figures are invisible by default.

Also fixes a bug where "clear all" killed the Server.

Finally, adds numpy as a dependency. 

Tested with both Matlab and Octave in Linux. 

Fixes #101.  Fixes #70.  Fixes #148.  Fixes #96.  Fixes #99.  Fixes #132.

### CODE REVIEW

**Comment by blink1073** [comment]
Ugh I hate you Coveralls!

**Comment by blink1073** [comment]
Do not merge yet!  I have to change messenger.c again.

**Comment by blink1073** [comment]
Good to go.  Octave plots were coming back from the dead so I had to add an explicit `close all hidden` at the start of each eval.

**Comment by blink1073** [comment]
Sorry, please wait again.

**Comment by blink1073** [comment]
Nevermind, I tried to avoid closing the figures by using `pause` instead of `drawnow` in `messenger.c` but the Octave figures still pop up.  This is ready to merge.

**Comment by arokem** [comment]
Just to be sure - these newly compiled messengers are now compiled against zmq 4?

**Comment by blink1073** [comment]
I compiled against libzmq3, since that is what is available via `apt-get` in Ubuntu 14.04.  I'd contrast this to the OSX situation where you have v4 available on Homebrew, and Windows, where you can get the installer on the ZMQ website.  (I built against v4 on Windows).

**Comment by isbadawi** [comment]
I went in the coveralls settings and changed "Coverage decrease threshold for failure" to "10%", so (if I understand the setting correctly) it should stop failing PRs for reducing coverage by a tiny amount like this. (You should both have access if you'd like to mess with the settings more: https://coveralls.io/r/arokem/python-matlab-bridge).

Anyway, this LGTM. I'll commit new versions of the OS X messengers for Matlab and Octave (built against v4) after merging.

**Comment by arokem** [comment]
Cool cool. I am working on setting up the messengers right now, so you can
hold off on that.

**Comment by isbadawi** [comment]
Oh sorry! I just pushed them. Feel free to override if you have something you want to add.

**Comment by arokem** [comment]
No problem. The ones you pushed are compiled against zmq 4? I'll add (as
backup) the zmq 3 ones.

**Comment by isbadawi** [comment]
Yep, I built them against 4.0.5.

**Comment by arokem** [comment]
OK. Working on those zmq3 messngers for the mac. Will have a PR with that
soon.

**Comment by blink1073** [comment]
I should build some zmq 4 ones for linux as well. 



—

**Pull request merged**
