### PR TITLE
Dhermes travis pypi

### PR DESCRIPTION
**Pull request by arokem**
@dhermes - how does this look to you? 

If you think this is ready to go, I will merge it. 

Then, we can close #113

### CODE REVIEW

**Comment by arokem** [comment]
Hmm. Apparently not: https://travis-ci.org/arokem/python-matlab-bridge/builds/48195292

Any ideas?

**Comment by dhermes** [comment]
I suppose we need to add a do nothing script. My bad.

How about something like this (added to `.travis.yml`):

```yaml
script:
  - true
```

If you have unit tests you'd like to run you could add a section for that as well.

**Comment by arokem** [comment]
That would require matlab...

**Comment by dhermes** [comment]
Haha yes I thought about this a bit. Doesn't seem to be worth the effort.

**Comment by isbadawi** [comment]
You could maybe run the tests under Octave (set USE_OCTAVE=1 environment
variable)?

**Comment by isbadawi** [comment]
It would probably be trickier than that actually. I'll look into myself
later.

**Comment by arokem** [comment]
I'll merge this one for now. I think that we should put out a new release/tag soon anyway, so we will get to try this out!

**Pull request merged**
