### PR TITLE
Streamline eval functions

### PR DESCRIPTION
**Pull request by blink1073**
Major streamline of the eval logic on both the python and matlab ends.  Consolidates to a single path.

Only API change: there is no more `content.code` output parameter for `run_code` calls.

### CODE REVIEW

**Comment by blink1073** [comment]
Okay, I'm done fiddling.

**Comment by blink1073** [comment]
That's my kind of PR:  5 times as many deleted lines as added!

**Comment by blink1073** [comment]
Question: does `eval` need to exist at all since it can be called using `feval` similar to `get_variable`?  The only downside I see is we'd lose the `content.code` parameter in the return value.

**Comment by blink1073** [comment]
The symmetry was too good to pass up.

**Comment by blink1073** [comment]
I don't know what is going on with Coveralls all of a sudden.

**Comment by isbadawi** [comment]
Coveralls is just complaining the coverage % went down (just barely), but whatever.

LGTM.

**Comment by blink1073** [comment]
I've seen coverage drop before and it did not call it a failure, maybe they changed their policy (I hope not).

**Pull request merged**
