### PR TITLE
BF: Install on Windows 64 systems, but not on 32 bit Windows.

### PR DESCRIPTION
**Pull request by arokem**
At least until someone helps us build the messenger for that system.

This should help with #122

### CODE REVIEW

**Comment by mmagnuski** [comment]
I have a 32-bit python installed (mainly because psychopy declares not to work on 64 bit python) on a 64 bit windows. In this scenario both sys and platform return 32 bit:
```python
import sys
sys.platform
Out[2]: 'win32'

import platform
platform.architecture()
Out[4]: ('32bit', 'WindowsPE')
```

Checking for maxint also does not work in this context:
```python
maxint = sys.maxint()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-8213151cd894> in <module>()
----> 1 maxint = sys.maxint()

TypeError: 'int' object is not callable

maxint = sys.maxint
maxint
Out[12]: 2147483647
```
However, checking `platform.machine()` works well:
```python
platform.machine().endswith('64')
Out[5]: True
```

So if 32 bit python running on 64 bit windows is ok, I would consider checking system architecture with `platform.machine()`.

**Comment by arokem** [comment]
Thanks @mmagnuski for checking this! Does the recent commit work for you? 

As you might understand, I don't have a Windows machine to test this on, so I rely heavily on help from people like you!

**Comment by mmagnuski** [comment]
I completely understand, windows drives me crazy sometimes. :smile: 
You forgot to `import platform` so currently this branch gives an error.
After adding the import pymatbridge installs seemingly well.
However, there is still a problem. `mlab.start()` brought up a matlab instance window saying:
```matlab
Invalid MEX-file 'D:\Python\Anaconda\lib\site-packages\pymatbridge\matlab\messenger.mexw64': Nie można odnaleźć określonego modułu.
Error in matlabserver (line 7)
messenger('init', socket_address); 
```
I would like to help here but I'm not sure if I can - I have never done any C or mex.
Why would the mex file be invalid? 
The part of the error that is in polish reads something like "could not find specified module".
Could I be missing something on the matlab part or is it that the pymatbridge mex files were not correclty installed?

**Comment by mmagnuski** [comment]
I will try compiling messenger.c to mex in the nex few days (will have to figure how to do it) and see if this helps. But this seems to be unrelated to this pull request, so I think it would be better if I opened a new issue for this `Invalid MEX-file` error.

**Comment by arokem** [comment]
Oh - oops - thanks for pointing that out.

As for your mex error, I sort of know what "nie mozna" means, but what does
the rest mean? :-)

For building the messenger on your system, you might want to refer to these
notes:
http://stackoverflow.com/questions/23716426/installing-pymatbridge-on-windows

**Comment by arokem** [comment]
Just to be sure - is this branch ready to merge from your point of view?

**Comment by mmagnuski** [comment]
Thanks for the resources, they will be very useful.
 (The meaning of the 'nie mozna' error (its in polish) is something like: "could not find specified module").
Yes, I think the installation should work well on 64 bit windows now. Ready to merge, sir! :)

**Comment by arokem** [comment]
Hmm. I wonder what `module` it's referring to.

**Comment by arokem** [comment]
Just for the record: what is your Matlab version? In case that ends up being a meaningful variable here.

**Comment by mmagnuski** [comment]
Sorry for the delay - my matlab version:
```
MATLAB Version: 8.0.0.783 (R2012b)
```
I will report soon on my progress :)

**Comment by willard-yuan** [comment]
@mmagnuski , I also encountered this type of problem in windows, the error is the same to you:

```sh
Invalid MEX-file 'D:\Python\Anaconda\lib\site-packages\pymatbridge\matlab\messenger.mexw64': .
Error in matlabserver (line 7)
messenger('init', socket_address); 
```
image

The version of my python is as follows:
image

and my matlab version is also `MATLAB Version: 8.0.0.783 (R2012b)`

I run the package *python-matlab-bridge* in Ubuntu 14.04 successfully, but the problem in the window 7 still unsolved.

**Comment by franktoffel** [comment]
Hi, I am having the same issue with windows 7 and Anaconda:

    ValueError: pymatbridge does not work on win32

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\fran
z\AppData\Local\Temp\pip-build-9c9zsay6\pymatbridge

This is my Python information:
C:\Users\franz>python
Python 3.4.2 |Continuum Analytics, Inc.| (default, Jan  9 2015, 10:32:40) [MSC v
.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by arokem** [comment]
First question: are you installing from a recent version of pymatbridge?
If the answer to that question is "yes", what happens if you type the following in a python session?

    import sys
    print(sys.platform)
    import platform
    print(platform.machine())

**Comment by franktoffel** [comment]
Hi! I've just tried to install pymatbridge via pip so I guess the answer is
"yes".

This is the output I get with the code you mention:
    print(sys.platform)
    win32

    print(platform.machine())
    AMD64



On Tue, Mar 3, 2015 at 8:47 PM, Ariel Rokem <notifications@github.com>
wrote:

> First question: are you installing from a recent version of pymatbridge?
> If the answer to that question is "yes", what happens if you type the
> following in a python session?
>
> import sys
> print(sys.platform)
> import platform
> print(platform.machine())
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arokem/python-matlab-bridge/pull/123#issuecomment-77019952>
> .
>



-- 

*Francisco J. Navarro-Brull*

**Comment by arokem** [comment]
That confuses me. Would you mind trying to install this from the source? 

That would entail downloading the current source code (https://github.com/arokem/python-matlab-bridge/archive/master.zip) and running

    python setup.py install 

in the source directory.

**Comment by franktoffel** [comment]
Ok, from source worked :)

But... now I get this in the MATLAB console :(

    Invalid MEX-file
'C:\Users\franz\Anaconda3\envs\imatlab\lib\site-packages\pymatbridge\matlab\messenger.mexw64':
The specified module
could not be found.

On Tue, Mar 3, 2015 at 9:36 PM, Ariel Rokem <notifications@github.com>
wrote:

> That confuses me. Would you mind trying to install this from the source?
>
> That would entail downloading the current source code (
> https://github.com/arokem/python-matlab-bridge/archive/master.zip) and
> running
>
> python setup.py install
>
> in the source directory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arokem/python-matlab-bridge/pull/123#issuecomment-77029038>
> .
>



-- 

*Francisco J. Navarro-Brull*

**Comment by arokem** [comment]
Well, progress, but so sorry that it isn't working yet. This might be an
issue with the version of zmq that you have installed.

Could you please tell me what you get when you type:

    import zmq
    print(zmq.zmq_version())


Hey @blink1073 - could you confirm that this was built against zmq3? Do you
still have access to the machine on which you built the Windows messenger?
Maybe we could build the zmq4 ones for this platform as well?

There's this page on SO, describing how to build the messenger yourself on
Windows, but I am not sure that it's up-to-date:

http://stackoverflow.com/questions/23716426/installing-pymatbridge-on-windows

**Comment by franktoffel** [comment]
print(zmq.zmq_version())
    4.0.5

**Comment by blink1073** [comment]
@arokem, I did not build the Matlab mex for Windows, since I only have a Linux version.

**Comment by arokem** [comment]
Indeed, it looks like @aebrahim did that here:
https://github.com/arokem/python-matlab-bridge/commit/ca59b30b136ae40dabfd7382c3b45a7245da003c

If you're still around, @aebrahim: could we ask for your help building the
Windows messenger with zmq 4?

Although, how did you get the Octave messenger for Windows, without a
Windows machine?
https://github.com/arokem/python-matlab-bridge/blob/master/messenger/mexw64/messenger.mex

**Comment by aebrahim** [comment]
I'll take a crack at that this weekend.

**Comment by blink1073** [comment]
@arokem, I have a Windows machine, just no Windows Matlab.  :smile:

**Comment by arokem** [comment]
Aha! Of course - that explains. Oh well, let's wait for @aebrahim to take a
shot at this (thanks for the swift reply, and TIA for taking a crack at
it!).

**Comment by arokem** [comment]
Hey @aebrahim - any luck with this?

**Comment by aebrahim** [comment]
Sorry for the delay. See #161

**Comment by arokem** [comment]
@franktoffel - this is now merged into master, could you try reinstalling from master?

**Comment by franktoffel** [comment]
Hi @arokem, I have just tried the installation from master (the installation worked fine). I am still unable to connect due to a problem with the mex files (albeit these files exist). This is the error I've got on the matlab command window:

```
Invalid MEX-file 'C:\Users\franz\Anaconda3\envs\imatlab\lib\site-packages\pymatbridge\matlab\messenger.mexw64': The specified procedure
could not be found.
```

**Comment by mmagnuski** [comment]
I am having the same error. Installed from master, installation was ok but mex still does not work.

**Comment by aebrahim** [comment]
Ok. Strange because it worked for me. What matlab version?

**Comment by mmagnuski** [comment]
My matlab version:
```
>> version
ans =
8.0.0.783 (R2012b)
```
My zmq version:
```python
print(zmq.zmq_version())
4.0.5
```
I have 64 bit windows 8 and 32 bit python (2.7) - I am not sure if this is relevant, but try to always mention it just to be on the safe side.

**Comment by aebrahim** [comment]
Did MATLAB break some binary compatibility or something? I have the
opposite problem you do - I can use the new mex but not the old mex on
R2014b.

**Comment by aebrahim** [comment]
In fact, it runs for me in R2014b but not R2013a.

**Comment by aebrahim** [comment]
I built this with 2013a... does it work any better?

https://drosophi.la/messenger.mexw64

**Comment by franktoffel** [comment]
With R2014a (Classroom license) didn't work before. I didn't try with yours, @aebrahim

**Comment by mmagnuski** [comment]
Matlab 2014b changes the way handles work in graphics and generally redesigns graphic internals, but I am not aware if this entails binary incompatibility.

Regarding the mex file - it works!  :hamster: :+1:
So while I am really happy the mex works for me, the code still throws an error. 
I got `Matlab failed to start.` error, but matlab did start and seems to be connected (matlab window says `Socket created at: tcp://127.0.0.1:55555`). 
Matlab startup was (and usually is) pretty slow, so I thought that maybe pymatbridge does not wait long enough for the connection to be established?
The problem may be in this part of `is_connected` method:
```python
def is_connected(self):
        if not self.started:
            time.sleep(2)
            return False
```
What is the `time.sleep` supposed to do here? Maybe the intent was to sleep for some time and check again? Currently it sleeps and returns `False` anyway.

**Comment by mmagnuski** [comment]
A success (with yet another error :) ):
- I restart the kernal
- I leave previously opened matlab window open
- I start python-matlab connection:
```python
from pymatbridge import Matlab
mlab = Matlab()
mlab.start()
```

This quickly connects to matlab (probably because one matlab instance was connected to the socket already) and everything works (`run_code`, `get_variable` etc.)
**BUT** pymatbridge spawned another matlab instance that failed to connect, the error in matlab window says:
```
Error using messenger
Socket creation failed.
Error in matlabserver (line 7)
messenger('init', socket_address); 
```
So it may be useful not to spawn another matlab instance in this case (although it is harmless).

Anyway - the mex file works, and python and matlab can finally speak to each other. :dancers:

**Comment by mmagnuski** [comment]
Just to clarify which mex works for me - the one built on matlab 2013b by @aebrahim

**Comment by mmagnuski** [comment]
(BTW - `%load_ext pymatbridge` also creates another matlab instance, although one connected is already present. It probably requires another issue)

**Comment by aebrahim** [comment]
OK I'll create a pull request using the new file.

**Comment by aebrahim** [comment]
Wait there never was a 2013b. There is 2013a and 2014b. Which did you mean?

**Comment by mmagnuski** [comment]
Sorry, 2013a.

**Comment by DeepGravity** [comment]
Hi,
I'm from 2020. 

I have the same issue. and followed all mentioned tricks, but it did not work. 

this is my error:

> CalledProcessError: Command '['C:\\Program Files\\MATLAB\\R2019a\\bin\\mex', '-O', '-LC:\\Users\\USER\\Anaconda3\\pkgs\\zeromq-4.3.2-h6538335_2\\Library\\lib', '-IC:\\Users\\USER\\Anaconda3\\pkgs\\zeromq-4.3.2-h6538335_2\\Library\\include', '-lzmq', './src/messenger.c', '-DZMQ_STATIC']' returned non-zero exit status 4294967295.

**Pull request merged**
