### PR TITLE
Update messenger.mex for ubuntu.

### PR DESCRIPTION
**Pull request by isbadawi**
Compiled against latest octave. Should hopefully fix the Travis build.

### CODE REVIEW

**Comment by isbadawi** [comment]
Seems I compiled against the wrong version of zmq. I'll try this again...

**Comment by isbadawi** [comment]
Third time's the charm...

This fixes the octave failure, now there is an error about `import IPython.nbformat.v4 as nbformat` which I guess is what #213 is trying to fix. I'll merge this one.

This is good for the travis build, but I'm not sure what the right thing to do is here for users. Do we need different versions of messenger.mex for different octave versions, as well as different zmq versions?

**Comment by arokem** [comment]
Thanks so much for jumping in with this @isbadawi! And apologies for being AWOL last few weeks.

**Comment by arokem** [comment]
Concerning the generally right thing to do: I think that we should go with support for recent versions of Octave and zmq. It's a stretch to support every possible combination. I have had trouble compiling the messenger against newer octave on my mac so far, but will keep trying...

**Pull request merged**
