### PR TITLE
Add Travis Testing against Octave

### LINKED ISSUE #138: Double scalars not handled by Octave
Simple test case yields `1` instead of `1.5`:

```
o = Octave()
o.start()
o.run_code('a=1.5')
o.get_variable('a')
```

This appears to be a limitation when calling `javaObject('org.json.JSONObject').toString()` in Octave.  I am using 3.8.1 in Ubuntu 14.04.  I traced `json_dump` and calling `toString()` on the `javaObject('java.lang.Double', value)` object works as expected, but not when it is rolled into the full JSON object.

### PR DESCRIPTION
**Pull request by blink1073**
Closes #138.
Tests in 2.7 and 3.3 using Miniconda environments.
The 3.4 test was hanging at the end, but does not hang on my Ubuntu 14.04 install, so I removed it.
Current coverage is 80%.  I'll add some more tests in another PR.

### CODE REVIEW

**Comment by isbadawi** [comment]
Some notes as you're working on this -- I did go through a bit of this before:

* I would use `ppa:octave/stable` instead of `ppa:picaso/octave`. The latter is only on 3.6.1 -- IIRC Java support became default only in Octave 3.8 (before that it was a separate package). That's also why you get the error about `--no-gui`.
* The magic tests still use Matlab even if `USE_OCTAVE=1`. Either exclude them or fix the magic to support Octave too

**Comment by blink1073** [comment]
Thanks!

**Comment by blink1073** [comment]
Note to self: add something in `setup.py` to handle the mex file.

**Comment by blink1073** [comment]
By the way @isbadawi, Octave magic is now working :smile:

**Comment by blink1073** [comment]
Ready to roll!

**Comment by isbadawi** [comment]
Looks good overall, but I'm not sure I like the Octave and Ubuntu specific `make.py` you added. I think it would be better to generalize the other `make.py` so that it can build the Octave messenger if needed. I also feel like installing system dependencies shouldn't be `make.py`'s responsibility.

We can address that later though -- getting tests to run on Travis is more important. Thanks for working on this!

**Comment by blink1073** [comment]
I agree it is a bit of a hack, my plan was to get it working on Windows next and devise a more general solution.  I do not have access to a Mac.  I agree the apt-get belongs in the documentation as opposed to the make file.

**Comment by arokem** [comment]
First of all, this is great.

Second - this Octave thing now doesn't work on my machine (a mac), because
of that apt-get. If this is just for travis, can't we move the apt-get into
the `.travis.yml` file, and then set up whether you use the matlab for mex
generation or octave with `mkoctfile` through the `local.cfg` file?

**Pull request merged**
