### PR TITLE
RF: Check for nargout.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by blink1073** [comment]
You're using the matlab constant `nargout` here, which is always 1 for this function.  Like I said, we need to pass in the desired `nargout` (and name it something else).

**Comment by arokem** [comment]
Closed in favor of https://github.com/arokem/python-matlab-bridge/pull/136

**Comment by blink1073** [comment]
I think you still need this PR since my PR is against yours.

**Comment by arokem** [comment]
Oops

**Comment by arokem** [comment]
OK - I merged yours in here. I can write those tests.

**Comment by blink1073** [comment]
Ha, okay, on a day trip with the fam.

**Comment by arokem** [comment]
Happy Valentine's Day!

On Sat, Feb 14, 2015 at 10:22 AM, Steven Silvester <notifications@github.com

**Comment by blink1073** [comment]
Looks good to me, Happy Valentine's Day!

**Pull request merged**
