### PR TITLE
Minor mex make fixes

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by arokem** [comment]
This is much needed. However, it's not working on python3. I am still trying to make this work for python3 and will merge as soon as I can make it go.

**Comment by jakirkham** [comment]
What's the error that you are getting? I don't have a working copy of python3 on hand.

**Comment by arokem** [comment]
Please take a look here: #112 - it integrates my python 3 fixes, on top of your commits. Does this look good to you?

**Comment by jakirkham** [comment]
Yep, works fine for me. I was wondering if it was an encoding issue.

**Comment by jakirkham** [comment]
Closed in favor of #112.

**Pull request closed without merging**
