### PR TITLE
Unify variable visibility and optionally leave in MATLAB

### PR DESCRIPTION
**Pull request by nzjrs**
Based on the original pythonic branch by Hildon Bristow this branch adds more flexibility in how variables returned from functions are handled (576ee23). This is best demonstrated with an example

```python
x,y = mlab.meshgrid(range(1,4),range(10,15),nout=2)
```
returns the two matrices to the python side
```python
placeholder = mlab.meshgrid(range(15,20),range(10,15),nout=2,saveout=('X','Y'))
```
saves the two output variables as X and Y in MATLAB. Subsequently one can do
```python
mlab.run_code('Z=X+Y')
z = mlab.get_variable('Z')
```
and so on. This saves the serialization penality when one wishes to generatively or programatically call MATLAB code from python without necessarily wanting to generate whole matlab m files.

This required a few other changes, such as unifying run_code, run_script and run_function in such a way that they are all executed in the base workspace so variables can be shared (a07604a, 3993679, e315ad0).

I also added logging (cdaded9) and the ability to show MATLAB stdout (3a880cf).

Finally, due to the ambiguity of passing and returning adjacent matrix arguments via textual JSON, all arguments are passed via dictionaries/structures and converted on appropriately (7d38469)

The obvious extension to this work is to extend the ```placeholder``` listed above to be a true proxy type. When this proxy type is passed across the python/MATLAB boundary it would be done only as a reference and the value filled out appropriately on the MATLAB side. Similarly, on the python side any attempt to perform arithemetic with the proxy type would return its true value (e.g. https://pypi.python.org/pypi/ProxyTypes)

### CODE REVIEW

**Comment by nzjrs** [comment]
Good to see the other stuff merged. I should take a look and rebase this branch again.

I have been using my fork for a while now, and things seem to be working very well.

**Comment by blink1073** [comment]
@nzjrs, I believe the only thing we haven't covered is the proxy idea.  You are welcome to create a new PR that implements that piece.

**Comment by arokem** [comment]
Yes - it would be great if you could rebase on the current master, and make a PR from the difference. Note that many other things have changed, and merging into your fork might be tricky. @blink1073 has been on fire for the last few days.

**Comment by blink1073** [comment]
It looks like we also need:
I also added logging (cdaded9) and the ability to show MATLAB stdout (3a880cf).

**Comment by nzjrs** [comment]
@blink1073 Is the performance still not very good here because of the json serialisation? 

I go via /tmp files for large arrays in my branch.

**Comment by blink1073** [comment]
we are using base64 to encode numpy arrays, which is ~10X faster than the old way for floating points, and does not rely on the file system.

**Comment by arokem** [comment]
See here: https://github.com/arokem/python-matlab-bridge/pull/103

On Wed, Feb 18, 2015 at 11:13 AM, Steven Silvester <notifications@github.com

**Comment by nzjrs** [comment]
@arokem, @blink1073 I tried that for large arrays, and the filesystem was faster (although maybe a little messy, although I clean up after myself IIRC). Thanks for the note though.

There are a few other things, like a fig decorator, and some other bits and pieces in other branches. I will have another look.

**Comment by blink1073** [comment]
If you can, please try and limit to one feature per PR to make it easier to review/merge.

**Comment by blink1073** [comment]
I used the filesystem route exclusively in Oct2Py, and I've found it to be more trouble than its work.  Typically passing arrays should not be the bottleneck, assuming the computation itself is what is expensive, just my 2 cents.

**Comment by nzjrs** [comment]
@blink1073 will do. I'm normally a polite pull request person (one feature per PR, etc), but this was more of a 'so it doesn't get lost kind of PR'.

I thought you might of been interested in my changes, as a real world user of this on large datasets. At the moment I am a in paper-preparation mode, so my free time is limited, but I might file some of my other changes later.

**Comment by blink1073** [comment]
Understood on all accounts.  If I get the itch, I'll fold in a few of your ideas, keep them coming.  :smile:

**Pull request closed without merging**
