### PR TITLE
Help installation along by stating the requirements.

### PR DESCRIPTION
**Pull request by arokem**
I think that pyzmq is the only hard requirement. Having numpy and ipython in
addition is probably useful, but not necessary.

### CODE REVIEW

**Comment by arokem** [comment]
Maybe one of the pip/travis experts could take a look? @dhermes?

**Comment by dhermes** [comment]
SGTM.

NumPy and SciPy are also dependencies. The `json` import fails for old enough versions of Python, but meh.

The `pymatbridge/matlab_magic.py` module has `IPython` as a dependency, but maybe this is optional?

**Comment by arokem** [comment]
SGTM? I will take that as a "go ahead". 

I believe that numpy and scipy are optional dependencies, but I admit that I am not sure what anyone would do with this, without them.

**Comment by dhermes** [comment]
http://www.urbandictionary.com/define.php?term=SGTM

As for optional dependencies, you can use `extras_require` in the setup file. For [example], see IPython.

[1]: https://github.com/ipython/ipython/blob/3e56f1a5d6d6da418bd8f3fc0f477f397f85498b/setup.py#L297

**Comment by arokem** [comment]
Got it. But why were you giggling? Maybe I'm missing something.

How's this?

**Comment by dhermes** [comment]
Looks good to me (LGTM). (By the way SGTM is "sounds good to me".)

**Comment by arokem** [comment]
Oh, sorry. urbandictionary was giving me "silently giggling to myself". I
swear.

I guess I gave you reason to giggle now.

At any rate - merging

**Comment by dhermes** [comment]
Indeed. I shall commence with the giggling.

**Comment by arokem** [comment]
Seems like the travis thing is working:
https://pypi.python.org/pypi/pymatbridge

Release notes are here:
https://github.com/arokem/python-matlab-bridge/releases/tag/0.4.1

**Pull request merged**
